helm:
  parameters:
  - name: images.frontend.repository
    value: docker.io/bennimoser/k8s-multi-tenant-frontend
    forcestring: true
  - name: images.frontend.tag
    value: "20250701195150"
    forcestring: true
  - name: images.inventory.repository
    value: docker.io/bennimoser/k8s-multi-tenant-inventory
    forcestring: true
  - name: images.inventory.tag
    value: "20250706094436"
    forcestring: true
  - name: images.order.repository
    value: docker.io/bennimoser/k8s-multi-tenant-order-service
    forcestring: true
  - name: images.order.tag
    value: "20250701195151"
    forcestring: true
